"""Behavioral coverage for reader exports, source grounding, and plate previews."""
import contextlib
import io
from pathlib import Path
import sys
import tempfile
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / 'scripts'))
import compile as assembly
import chapter_pdf_local as renderer
import land
import package_check
import plate_check

SVG = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 430" '
       'aria-label="Mechanism %d"><text class="ttl" x="320" y="40">Mechanism %d</text>'
       '<text x="%d" y="180">A clean label</text></svg>')


def plate_svg(x, n=1):
    """A titled fixture valid under the author-ratified chapter title rule."""
    return SVG % (n, n, x)


def sources(root, n):
    chapter = root / 'book' / 'chapters' / f'ch{n:02}'
    chapter.mkdir(parents=True)
    (chapter/'refined.md').write_text(f'# Chapter {n}: Example\n\nProse end {n}.\n')
    (chapter/'distillation.md').write_text(
        f'# Chapter {n} Distillation\n\n**Mechanism:** Mechanism {n}\n'
        f'**Conversation sentence:** Conversation {n}.\n**Lesson:** Lesson {n}.\n'
        f'**Challenge:** Challenge {n}.\n**Practice:**\n1. Practice {n}.\n')
    run = root / 'runs' / f'ch{n:02}'
    run.mkdir(parents=True)
    (run/'plate.svg').write_text(plate_svg(100, n))
    return chapter, run


def export_safety_cases():
    out = []
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(tmp).resolve()
        ch, run = sources(root, 1)
        (run/'plate-brief.md').write_text(
            'The drawing carries the argument. Nothing here is invented.\n'
            '## Author additions\n\n- 2026-09-26 12:00: Your marriage lives there. '
            '[reader feedback, endorsed by the author 2026-09-26]\n'
            '## Other notes\n- 2026-09-26 12:01: Forbidden stray claim.\n')
        corpus = plate_check.corpus([str(ch)], str(run))
        for text, expected in [('Your marriage lives there', True), ('Lesson 1', True),
                               ('the drawing carries the argument', False),
                               ('endorsed by the author', False), ('Forbidden stray claim', False)]:
            ok = (plate_check.normalise(text) in corpus) == expected
            out.append((ok, 'grounding: '+text, 'only permitted source content enters the corpus', corpus))

        clean = '<section><h1>Chapter 1</h1><p>Reader prose.</p></section>'
        for label, extra, fails in [
            ('pagebreak', r'<p>\pagebreak</p>', True),
            ('newpage outside container', r'\newpage', True),
            ('escaped comment', '<p>&lt;!-- Generated by compile --&gt;</p>', True),
            ('fragmented marker', r'<p>\page<span>break</span></p>', True),
            ('hidden CSS and real comment', r'<style>/* \pagebreak */</style><!-- build note -->', False)]:
            p = root/'package.html'; p.write_text(clean+extra)
            defects, _ = package_check.check(str(p))
            out.append((any('leaked markup' in d for d in defects) == fails,
                        'package markup: '+label, 'inspect decoded visible text, not markup syntax', defects))

        # Exercise land.main's actual gate; only unrelated repository discovery is mocked.
        for name in ('refined.md', 'distillation.md'):
            (run/name).write_bytes((ch/name).read_bytes())
        (run/'verdict.md').write_text('Fixture approval\n')
        # land would refuse an existing chapter before reaching its plate check.
        (ch/'refined.md').unlink()
        (ch/'distillation.md').unlink()
        for x, force, expected in ((100, False, 0), (630, False, 1), (630, True, 0)):
            (run/'plate.svg').write_text(plate_svg(x))
            from okf_reconcile_cases import receipt
            rec = receipt(root, ['chapter:ch01'], ['runs/ch01/refined.md', 'runs/ch01/distillation.md'])
            args = ['land.py', '1', '--dry-run', '--okf-receipt', rec] + (['--force'] if force else [])
            with patch.object(land, 'REPO', str(root)), patch.object(sys, 'argv', args), \
                 patch.object(land.resolve_book, 'resolve', return_value=(str(root), '', '')), \
                 patch.object(land.resolve_book, 'inspect', return_value={'info':{'bookRoot':str(root/'book'),'bookRootRelative':'book'},'problems':[]}), \
                 patch.object(land.okf_gate, 'staged_link_defects', return_value=[]), \
                 contextlib.redirect_stdout(io.StringIO()) as output:
                rc = land.main()
            ok = rc == expected and not (ch/'refined.md').exists()
            if expected:
                ok = ok and 'geometry' in output.getvalue()
            out.append((ok, f'landing plate x={x} force={force}',
                        'bad geometry refuses before writes; clean and explicit override still work', output.getvalue()))

        # A matching title passes; either visible or accessible mismatch must FAIL.
        for label, svg in [
            ('visible', plate_svg(100).replace('>Mechanism 1</text>', '>Other title</text>')),
            ('accessible', plate_svg(100).replace('aria-label="Mechanism 1"', 'aria-label="Other title"'))]:
            (run/'plate.svg').write_text(svg)
            rows = plate_check.rows(str(run/'plate.svg'), chapter=1,
                                    book_root=str(root/'book'), runs_root=str(root/'runs'), render=False)
            title_status = next(status for status, name, detail in rows if name == 'title')
            out.append((title_status == 'FAIL', 'ratified title rejects '+label+' mismatch',
                        'author-approved title rule must fail, not merely warn', title_status))

        # --force does not waive knowledge reconciliation, even with clean geometry.
        (run/'plate.svg').write_text(plate_svg(100))
        with patch.object(land, 'REPO', str(root)), patch.object(sys, 'argv', ['land.py', '1', '--force']), \
             patch.object(land.resolve_book, 'resolve', return_value=(str(root), '', '')), \
             patch.object(land.resolve_book, 'inspect', return_value={'info':{'bookRoot':str(root/'book'),'bookRootRelative':'book'},'problems':[]}), \
             contextlib.redirect_stdout(io.StringIO()) as output:
            rc = land.main()
        out.append((rc != 0 and 'receipt required' in output.getvalue() and not (ch/'refined.md').exists(),
                    'landing force cannot bypass OKF receipt', 'refuse before any book writes', output.getvalue()))

        (run/'plate.svg').write_text(plate_svg(630))

        # Compiler uses the exact selected draft, even when a clean landed file exists.
        for name, text in [('refined.md', '# Chapter 1: Example\n\nProse end 1.\n'),
                           ('distillation.md', (run/'distillation.md').read_text())]:
            (ch/name).write_text(text)
        sources(root, 2)
        (root/'book/03-outline.md').write_text('## PART I — Example\n\n## Chapter 1\n\n## Chapter 2\n')
        landed = root/'book/design/plates'; landed.mkdir(parents=True)
        (landed/'clean.svg').write_text(plate_svg(100))
        with patch.object(assembly, 'REPO', str(root)), \
             patch.object(sys, 'argv', ['compile.py','--plates','--no-pdf','--outdir',str(root/'out')]), \
             patch.object(assembly.resolve_book, 'resolve', return_value=(str(root), '', '')), \
             patch.object(assembly.resolve_book, 'inspect', return_value={'info':{'bookRootRelative':'book'}}), \
             contextlib.redirect_stdout(io.StringIO()) as output:
            rc = assembly.main()
        md = (root/'out/manuscript.md').read_text()
        out.append((rc == 0 and 'runs/ch01/plate.svg | plate_check: FAIL geometry' in output.getvalue(),
                    'compiler checks selected SVG', 'report failure without blocking export or selecting a different file', output.getvalue()))
        with patch.object(plate_check, 'rows', return_value=[('FAIL', 'ink', 'edge pixels')]) as checker:
            report = assembly.selected_plate_report(str(run/'plate.svg'), render=True)
        out.append((checker.call_args.args[0] == str(run/'plate.svg')
                    and checker.call_args.kwargs['render'] and 'FAIL ink' in report,
                    'PDF export requests ink check', 'surface raster failures on the selected file', report))
        for n in (1,2):
            start = md.index(f'# Chapter {n}:')
            dist = md.index(f'data-chapter="{n}"', start)
            ok = start < md.index(f'ch{n:02}/plate.svg', start) < dist
            ok = ok and all(f'{field} {n}' in md[dist:] for field in ('Mechanism','Conversation','Lesson','Challenge','Practice'))
            if n==1:
                ok = ok and dist < md.index('# Chapter 2:')
            out.append((ok, f'complete chapter {n} sequence', 'prose then selected plate then every distillation field', md))
        with patch.object(renderer, 'rasterise_plates', side_effect=lambda md,*a:md), \
             patch.object(renderer, 'render_html', side_effect=lambda body,*a:body):
            html = renderer.build(md, None, [], str(root/'book.pdf'), 'Fixture')
        p=root/'collection.html';p.write_text(html)
        defects,_=package_check.check(str(p))
        out.append((not defects and html.count('class="chapter-bundle"')==2,
                    'collection distillations pass package structure', 'each complete distillation ends its own chapter bundle', defects))
        # Append inside the bundle after, not inside, the distillation.
        p.write_text(html.replace('</section></section>', '</section><p>Late chapter prose.</p></section>', 1))
        defects,_=package_check.check(str(p))
        out.append((any('must be last' in d for d in defects), 'collection rejects prose after distillation',
                    'allowing collections must not permit late chapter content', defects))
    return out


def raster_cases():
    out=[]
    with tempfile.TemporaryDirectory() as tmp:
        root=Path(tmp); svg=root/'band.svg'
        svg.write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200"><rect x="0" y="190" width="200" height="10" fill="black"/></svg>')
        for scale in (2,3):
            png=root/f'band-{scale}.png'
            renderer.svg_to_png(str(svg),str(png),scale=scale)
            w,h,bpp,pixels=plate_check.png_rows(str(png))
            dark=sum(sum(row[x:x+3])<384 for row in pixels[190*scale:] for x in range(0,w*bpp,bpp))
            out.append((w==h==200*scale and dark>=200*10*scale*scale*.99,
                        f'raster bottom band survives at {scale}x', 'correct dimensions alone do not prove an uncropped image', dark))
            out.append((plate_check.raster_current(str(svg),str(png)), f'preview current at {scale}x',
                        'compare at the PNG scale rather than renderer default', str(png)))
        svg.write_text(svg.read_text().replace('fill="black"','fill="red"'))
        out.append((not plate_check.raster_current(str(svg),str(root/'band-2.png')),
                    'changed pixels make preview stale','same dimensions do not imply current content',''))
        report=plate_check.rows(str(svg),preview=str(root/'band-2.png'))
        out.append((any(status=='WARN' and name=='raster-current' for status,name,_ in report),
                    'preview freshness has a checker caller','staleness is surfaced by rows, not only a helper',report))
    return out


if __name__=='__main__':
    rows=export_safety_cases() + (raster_cases() if '--render' in sys.argv else [])
    for ok,name,why,detail in rows:
        print(('[ ok ] ' if ok else '[FAIL] ')+name)
        if not ok:print(detail)
    print('%d/%d export cases pass.' % (sum(bool(r[0]) for r in rows),len(rows)))
    raise SystemExit(0 if all(row[0] for row in rows) else 1)
