#!/usr/bin/env python3
"""
build_diagrams_page.py - assemble docs/diagrams.html from docs/diagrams/*.svg.

WHY A SCRIPT
    The three figures have to exist twice: as standalone .svg files an author can
    drop into a post, and inline in a page that can be published as one link.
    Two copies of a drawing with nothing keeping them equal is the same defect
    manual.py exists to prevent, so the page is derived from the files and the
    files are the source. Edit the SVG; rebuild the page.

    Captions live here rather than in the SVG because a standalone figure carries
    its own title inside the drawing, while the page wants the longer claim under
    it. The drawing is the figure; the caption is the argument.

USAGE
    python3 scripts/build_diagrams_page.py
"""

import io
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
SRC = os.path.join(REPO, "docs", "diagrams")
OUT = os.path.join(REPO, "docs", "diagrams.html")

FIGURES = [
    ("01-automation-boundary.svg",
     "Find the boundary before you build anything",
     "The expensive question is not <em>can a model write this</em>. It is <em>where does the "
     "material actually come from</em>. Everything upstream of a good research brief needs the "
     "author in the room, because that is where the ideas are. Everything downstream can run "
     "cold, with no conversation and no context. Draw that line for your own work first: it "
     "tells you which stages are worth automating and which ones you would only be automating "
     "the appearance of."),
    ("02-nobody-grades-themselves.svg",
     "A producer never reports its own score",
     "Counted rules were self-reported for three chapters, and the numbers were wrong every "
     "time - once hiding a live violation while four editing passes reported clean. The fix is "
     "one node and one prohibition: a script counts, its output is pasted verbatim rather than "
     "summarised, and the desk that wrote the prose never supplies the number. The Publisher "
     "then runs the same script again, independently, and a disagreement between the two "
     "reports is itself a finding. Two failed rounds send the question to the author rather "
     "than starting a third."),
    ("03-derived-not-remembered.svg",
     "Anything that describes the system should be generated by it",
     "Four files in this repo each stated how many desks it has. Three were wrong, and every "
     "one of them had been correct on the day it was typed. No amount of discipline fixes that, "
     "because the failure is not forgetfulness - it is that a hand-written description of a "
     "moving system is a snapshot pretending to be a fact. The manual is now read out of the "
     "repository by a script, and a check run at the end of every session fails when the source "
     "has changed and the page has not. The author stopped having to remember."),
]

PAGE = """<title>Three Diagrams of the House</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600&family=Public+Sans:wght@400;500;600&display=swap">
<style>
:root{
  --paper:#fbfaf7; --ink:#17151a; --ink-2:#4a4750; --ink-3:#7b7884; --rule:#dcd9d1;
  --author:#b8412f; --pencil:#2f5fa8; --figure-ground:#fbfaf7;
  --display:'Fraunces',Georgia,'Times New Roman',serif;
  --body:'Public Sans',-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif;
}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){
  --paper:#14161a; --ink:#ece9e2; --ink-2:#bdb8ae; --ink-3:#8a8780; --rule:#2c3038;
  --author:#e07a66; --pencil:#7ea3e6;
}}
:root[data-theme="dark"]{
  --paper:#14161a; --ink:#ece9e2; --ink-2:#bdb8ae; --ink-3:#8a8780; --rule:#2c3038;
  --author:#e07a66; --pencil:#7ea3e6;
}
*{box-sizing:border-box}
body{margin:0;background:var(--paper);color:var(--ink);font-family:var(--body);
  font-size:16px;line-height:1.55;-webkit-font-smoothing:antialiased}
.wrap{max-width:940px;margin:0 auto;padding-inline:20px;padding-block:3rem 4rem}
h1{font-family:var(--display);font-weight:600;font-size:clamp(2rem,6vw,3.2rem);
  line-height:1.1;margin:0 0 .5rem;letter-spacing:-.015em;text-wrap:balance}
.eyebrow{font-size:.72rem;font-weight:600;letter-spacing:.14em;text-transform:uppercase;
  color:var(--ink-3);margin-bottom:.7rem}
.lede{font-size:1.1rem;color:var(--ink-2);max-width:60ch;margin:0 0 .6rem}
header{border-bottom:1px solid var(--rule);padding-bottom:2.2rem;margin-bottom:.5rem}
figure{margin:3rem 0 0}
.plate{background:var(--figure-ground);border:1px solid var(--rule);border-radius:10px;
  padding:.5rem;overflow-x:auto}
svg{display:block;width:100%;height:auto;min-width:560px}
figcaption{margin-top:1.1rem;max-width:64ch}
figcaption b{display:block;font-family:var(--display);font-weight:600;font-size:1.3rem;
  line-height:1.2;margin-bottom:.4rem;color:var(--ink);text-wrap:balance}
figcaption span{color:var(--ink-2);font-size:.97rem}
.count{font-family:var(--display);font-size:.85rem;color:var(--ink-3);
  border-top:1px solid var(--rule);padding-top:.5rem;margin-bottom:.9rem;
  display:flex;justify-content:space-between;letter-spacing:.02em}
footer{margin-top:3.5rem;padding-top:1.4rem;border-top:1px solid var(--rule);
  color:var(--ink-3);font-size:.9rem;max-width:64ch}
footer em{color:var(--ink-2);font-style:normal}
@media (max-width:560px){ .plate{padding:.35rem} }
</style>

<div class="wrap">
<header>
  <div class="eyebrow">A book production house, in three pictures</div>
  <h1>What we learned building a writing system</h1>
  <p class="lede">These are the three decisions that mattered. Each one came from a failure
  that shipped first, and each is the part a second team would otherwise have to rediscover.</p>
</header>
{{FIGURES}}
<footer>
  <p>Drawn from a working system: a book production house where the author is in the room for
  two things - saying what the chapter is, and saying whether it landed - and everything
  between runs as cold sub-agents and scripts that cannot be talked past.</p>
  <p><em>Each figure is a standalone SVG.</em> The drawings are the source and this page is
  generated from them, which is the third diagram applied to itself.</p>
</footer>
</div>
"""


def main():
    blocks = []
    for i, (fn, title, caption) in enumerate(FIGURES, 1):
        with io.open(os.path.join(SRC, fn), encoding="utf-8") as fh:
            svg = fh.read().strip()
        # Strip the XML namespace declaration: inline SVG in HTML needs no xmlns,
        # and leaving it in makes the markup look copied rather than authored.
        svg = svg.replace(' xmlns="http://www.w3.org/2000/svg"', "")
        blocks.append(
            '<figure>\n  <div class="count"><span>Figure %d of %d</span><span>%s</span></div>\n'
            '  <div class="plate">%s</div>\n'
            "  <figcaption><b>%s</b><span>%s</span></figcaption>\n</figure>"
            % (i, len(FIGURES), fn, svg, title, caption))

    page = PAGE.replace("{{FIGURES}}", "\n".join(blocks))

    # The page must not ship a figure whose drawing failed to inline.
    for fn, _, _ in FIGURES:
        if fn not in page:
            raise SystemExit("figure %s did not reach the page" % fn)
    if page.count("<svg") != len(FIGURES):
        raise SystemExit("expected %d inline drawings, found %d"
                         % (len(FIGURES), page.count("<svg")))
    if re.search(r"<figcaption><b></b>", page):
        raise SystemExit("a caption rendered empty")

    with io.open(OUT, "w", encoding="utf-8") as fh:
        fh.write(page)
    print("wrote %s (%d figures, %d bytes)"
          % (os.path.relpath(OUT, REPO), len(FIGURES), len(page)))


if __name__ == "__main__":
    main()
