#!/usr/bin/env python3
"""Render a chapter to PDF with headless Chromium.

The single approved PDF backend. chapter_pdf.py is a compatibility entry point.

Two choices are deliberate and worth stating:

  Plates are rasterised to high-DPI PNG rather than inlined as SVG. An SVG's
  labels become extractable text in a PDF, and the author listens to every
  chapter through a PDF-to-speech reader, which would read those labels aloud
  in the middle of a sentence. Raster keeps them printable and keeps them out
  of the audio.

  No running headers or footers, and no page numbers. Same reason: anything
  repeated on every page is read aloud on every page.
"""
import html as _html
import os
import re
import subprocess
import sys
from pathlib import Path
import shutil
from pdf_chapter_style import CSS as CHAPTER_CSS, format_headings

CHROME = os.environ.get("CHROME") or next((p for p in [
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/opt/pw-browsers/chromium-1194/chrome-linux/chrome",
    shutil.which("chromium"), shutil.which("google-chrome")
] if p and os.path.isfile(p)), "")
FLAGS = ["--headless", "--disable-gpu", "--no-sandbox", "--hide-scrollbars"]


def md_inline(t):
    t = _html.escape(t, quote=False)
    t = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", t)
    t = re.sub(r"(?<!\*)\*([^*]+?)\*(?!\*)", r"<em>\1</em>", t)
    t = re.sub(r"`([^`]+?)`", r"<code>\1</code>", t)
    # curly quotes and apostrophes, for print
    t = re.sub(r'"([^"]*)"', lambda m: "“" + m.group(1) + "”", t)
    t = t.replace("'", "’")
    return t


LABEL = re.compile(r"^\*\*[A-Z][A-Za-z ]{1,24}:\*\*")
DISPLAY_QUOTE = re.compile(r'^\*"(.+?)"\*\s*(?:\((.+)\))?\s*$')
PLATE_BLOCK = re.compile(r'^<(figure|div) class="plate">')
PLATE_IMG = re.compile(r'(<(?:figure|div) class="plate"><img src=")([^"]+\.svg)(")')
HTML_COMMENT = re.compile(r'^<!--.*-->$')
PAGEBREAK_DIV = '<div class="pb"></div>'
RAW_PASSTHROUGH = re.compile(r'^(<!--|<(figure|div) class="plate"|<div class="pb">)')


def rasterise_plates(md, base_dir, outdir):
    """Replace every plate block's SVG src with a PNG next to the output.
    The PNG name comes from the SVG's relative path, because every chapter
    plate is called plate.svg and basenames alone would overwrite each other."""
    def one(m):
        svg = os.path.normpath(os.path.join(base_dir, m.group(2)))
        stem = re.sub(r"[^A-Za-z0-9]+", "-", os.path.relpath(svg, base_dir)).strip("-")
        png = os.path.join(outdir, stem[:-4] + ".png" if stem.endswith("-svg") else stem + ".png")
        w, h = svg_to_png(svg, png)
        print(f"  plate rasterised: {os.path.basename(png)}  {int(w)}x{int(h)} @3x")
        return f'{m.group(1)}{os.path.basename(png)}" width="{int(w)}" height="{int(h)}{m.group(3)}'
    return PLATE_IMG.sub(one, md)


def md_to_html(md):
    out, lines, i = [], md.split("\n"), 0
    while i < len(lines):
        ln = lines[i]
        s = ln.strip()
        if not s:
            i += 1
            continue
        if s in ("---", "***", "___"):
            out.append('<hr class="beat">')
            i += 1
            continue
        if HTML_COMMENT.match(s):
            # compile.py's own provenance header ("<!-- Generated by... -->").
            # A real markdown/HTML pipeline (chapter_pdf.py) renders these
            # invisibly; this hand-rolled parser has no comment awareness at
            # all, so without this it fell into the paragraph branch below
            # and printed the escaped comment text as the PDF's first line.
            i += 1
            continue
        if s == PAGEBREAK_DIV:
            # compile.py's marker for "start fresh page here" (used before
            # the Putting It Into Practice section). Passed through raw; the
            # .pb CSS rule does the actual breaking.
            out.append(s)
            i += 1
            continue
        if PLATE_BLOCK.match(s):
            # compile.py --plates emits these already rasterised by build().
            out.append(s)
            i += 1
            continue
        m = re.match(r"^(#{1,4})\s+(.*)$", s)
        if m:
            lvl = len(m.group(1))
            out.append(f"<h{lvl}>{md_inline(m.group(2))}</h{lvl}>")
            i += 1
            continue
        if s.startswith("> "):
            buf = []
            while i < len(lines) and lines[i].strip().startswith("> "):
                buf.append(lines[i].strip()[2:])
                i += 1
            out.append("<blockquote><p>" + md_inline(" ".join(buf)) + "</p></blockquote>")
            continue
        if re.match(r"^\d+\.\s+", s):
            buf = []
            while i < len(lines) and re.match(r"^\d+\.\s+", lines[i].strip()):
                buf.append(re.sub(r"^\d+\.\s+", "", lines[i].strip()))
                i += 1
            out.append("<ol>" + "".join(f"<li>{md_inline(x)}</li>" for x in buf) + "</ol>")
            continue
        buf = []
        while i < len(lines) and lines[i].strip() and not re.match(
                r"^(#{1,4}\s|>\s|---$|\d+\.\s)", lines[i].strip()) and not RAW_PASSTHROUGH.match(lines[i].strip()):
            # A label line - "**Lesson:**", "**Challenge:**" - is its own
            # paragraph even when the source puts it on the very next line with
            # no blank between. Without this, Lesson and Challenge merge into
            # one block and the distillation reads as a wall.
            if buf and LABEL.match(lines[i].strip()):
                break
            buf.append(lines[i].strip())
            i += 1
        raw = " ".join(buf)

        # A paragraph that is nothing but an italicised quotation, optionally
        # followed by a parenthetical citation, is a display quote - the
        # chapter's Stoic anchor is written this way. Setting it as a
        # blockquote is what the author asked for when he asked that quotes be
        # formatted appropriately; left inline it reads as ordinary italics.
        q = DISPLAY_QUOTE.match(raw)
        if q:
            cite = f'<cite>{md_inline(q.group(2))}</cite>' if q.group(2) else ""
            out.append('<blockquote class="pull"><p>\u201c'
                       + md_inline(q.group(1)) + '\u201d</p>' + cite + "</blockquote>")
            continue

        para = md_inline(raw)
        cls = ' class="runin"' if para.startswith("<strong>") else ""
        out.append(f"<p{cls}>{para}</p>")
    return "\n".join(out)


_NODE_PATH = None


def node_modules():
    global _NODE_PATH
    if _NODE_PATH is None:
        env = os.environ.get("NODE_PATH")
        if not env:
            bundled = Path.home() / '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules'
            if bundled.is_dir():
                env = str(bundled)
        if env and os.path.isdir(os.path.join(env, "playwright")):
            _NODE_PATH = env
        else:
            r = subprocess.run(["npm", "root", "-g"], capture_output=True, text=True)
            _NODE_PATH = r.stdout.strip() if r.returncode == 0 else ""
    return _NODE_PATH


SHOT_JS = """
const [html, png, w, h, scale, exe] = process.argv.slice(1);
const { chromium } = require('playwright');
(async () => {
  const b = await chromium.launch({ executablePath: exe, args: ['--no-sandbox'] });
  const p = await b.newPage({ viewport: { width: +w, height: +h }, deviceScaleFactor: +scale });
  await p.goto('file://' + html);
  await p.screenshot({ path: png });
  await b.close();
})().catch(e => { console.error(e.message); process.exit(1); });
"""


def svg_to_png(svg_path, png_path, scale=3):
    """Rasterise an SVG at exactly its viewBox size.

    Chromium's own --screenshot with --window-size loses a fixed band at the
    bottom of every capture (the window includes chrome the viewport does
    not), which silently cut the last three lines off the Ch12 plate in the
    reader PDF and hid four plates' captions from the Designer. Found
    2026-09-20 by the plate-review desk, counting dark pixels. Playwright
    sets the viewport itself, so the capture is the canvas and nothing less.
    """
    src = open(svg_path, encoding="utf-8").read()
    m = re.search(r'viewBox="[\d.]+ [\d.]+ ([\d.]+) ([\d.]+)"', src)
    w, h = (float(m.group(1)), float(m.group(2))) if m else (640.0, 450.0)
    # The charset is not optional: without it Chromium sniffs the file, and
    # the Ch11 title's curly apostrophe came out as three garbage glyphs.
    wrap = f"<!doctype html><meta charset='utf-8'><style>*{{margin:0;padding:0}}body{{width:{w}px;height:{h}px}}svg{{display:block;width:{w}px;height:{h}px}}</style>{src}"
    tmp = png_path + ".html"
    open(tmp, "w", encoding="utf-8").write(wrap)
    env = dict(os.environ, NODE_PATH=node_modules())
    r = subprocess.run(["node", "-e", SHOT_JS, os.path.abspath(tmp), os.path.abspath(png_path),
                        str(int(w)), str(int(h)), str(scale), CHROME],
                       capture_output=True, text=True, timeout=120, env=env)
    os.remove(tmp)
    if r.returncode != 0:
        raise RuntimeError("svg_to_png: playwright capture failed: " + (r.stderr or r.stdout).strip()[-300:])
    return w, h


CSS = """
@page { size: 6in 9in; margin: 0.75in 0.7in 0.8in 0.7in; }
html { -webkit-print-color-adjust: exact; }
body { font: 10.5pt/1.62 Georgia,'Liberation Serif',serif; color:#1a1a1a;
       margin:0; text-rendering:optimizeLegibility; hyphens:auto; }

/* ---- the distillation card, first page ---- */
.dist { page-break-after: always; font-size:9.5pt; line-height:1.3; }
.dist.distback { page-break-before: always; page-break-after: auto; }
.dist .kicker { font: italic 9.5pt Georgia,serif; letter-spacing:.06em;
        color:#5a5a5a; text-align:center; margin:0 0 .08in; break-after:avoid; }
.dist h1 { font-size:14pt; font-weight:600; letter-spacing:.01em;
        text-align:center; line-height:1.25; margin:0 0 .08in;
        page-break-before:avoid; }
.dist .rule { width:2.2in; height:0; border-top:.6pt solid #bdbdbd;
        margin:.08in auto .10in; }
.dist .mech { text-align:center; font: 600 11pt Georgia,serif;
        letter-spacing:.14em; text-transform:uppercase; margin:0 0 .06in; }
.dist .convo { font: italic 11.5pt/1.55 Georgia,serif; text-align:center;
        margin:0 auto .3in; max-width:4in; color:#2a2a2a; }
.dist p { margin:0 0 .08in; }
.dist h2 { font:600 9.5pt Georgia,serif; letter-spacing:.16em;
        text-transform:uppercase; color:#5a5a5a;
        margin:.16in 0 .08in; border-bottom:.5pt solid #ddd; padding-bottom:.05in; }
.dist ol { margin:0 0 .1in; padding-left:.24in; }
.dist li { margin:0 0 .07in; }

/* ---- chapter ---- */
/* Every h1 (Prologue, Introduction, a Part opening, a Chapter) starts a
   fresh page in a whole-book compile, the same rule chapter_pdf.py already
   uses. compile.py used to insert a literal "\pagebreak" marker for this
   instead; neither renderer has ever understood that token, so it printed
   as visible text - this is the actual mechanism, not a marker to remember
   to strip. :first-of-type only avoids a break before the very first h1 in
   the whole document (they are all true DOM siblings under one <section>),
   so it does not create a blank leading page. */
h1 { font-size:20pt; font-weight:600; line-height:1.2; letter-spacing:.005em;
     margin:0 0 .06in; page-break-before:always; }
h1:first-of-type { page-break-before:avoid; }
h1 + hr.beat { display:none; }
/* compile.py's marker for "start fresh page here", used before the Putting
   It Into Practice section so a chapter's back matter never runs onto the
   same page as its closing lines. Zero height: it does not itself print. */
.pb { page-break-before:always; }
p { margin:0 0 .12in; text-align:left; text-indent:0; }
p.runin, p.runin + p, blockquote + p, .plate + p, hr.beat + p { text-indent:0; }
p.runin { margin-top:.2in; }
p.runin strong { font-weight:600; letter-spacing:.01em; }
hr.beat { border:0; height:0; margin:.24in auto; width:1.1in;
     border-top:.6pt solid #cfcfcf; }
blockquote { margin:.22in .42in; padding-left:.2in; border-left:1.2pt solid #d4d4d4; }
blockquote.pull { margin:.26in .3in; padding:0 0 0 .22in;
     border-left:1.6pt solid #c9c9c9; page-break-inside:avoid; }
blockquote.pull p { font: italic 11pt/1.56 Georgia,serif; }
blockquote cite { display:block; font: normal 9pt Georgia,serif; font-style:normal;
     color:#6a6a6a; margin-top:.09in; letter-spacing:.02em; }
blockquote p { font: italic 10.5pt/1.55 Georgia,serif; color:#2f2f2f;
     text-align:left; text-indent:0; margin:0; }
em { font-style:italic; }
strong { font-weight:600; }

/* ---- plate ---- */
/* A plate is a page a reader flips to, not a figure sitting in the running
   text - full isolation, same treatment the Part closing plates already
   get. Centred vertically as well as horizontally since it now owns the
   whole page. */
figure.plate { margin:0; text-align:center; page-break-before:always;
     page-break-after:always; page-break-inside:avoid;
     min-height:7.3in; display:flex; flex-direction:column;
     align-items:center; justify-content:center; }
figure.plate img { max-width:100%; max-height:6.8in; height:auto; }
figure.plate figcaption { font: italic 9pt Georgia,serif; color:#6a6a6a;
     margin-top:.1in; }
/* Part closing plate: a page of its own. 6x9 art on a 6x9 page with these
   margins leaves a 7.45in content box, so bound by height or the bottom
   spills onto the next page (the same lesson chapter_pdf.py records). */
div.plate { page-break-before:always; page-break-after:always; text-align:center; margin:0; }
div.plate img { max-height:7.3in; max-width:100%; width:auto; height:auto; }
.dropfirst::first-letter { font-size:1em; }
"""


def distillation_html(md, kicker):
    """One transform, two call sites. Extracted 2026-09-18: the front and back
    paths were 7 lines each and 5 identical, which is the two-copies-of-one-
    stylesheet shape that caused the defects this renderer exists to avoid."""
    d = md_to_html(md)
    d = re.sub(r"<h1>(.*?)</h1>",
               lambda m: f'<p class="kicker">{kicker}</p><h1>{m.group(1)}</h1>'
                         f'<div class="rule"></div>', d, count=1)
    d = re.sub(r"<p><strong>Mechanism:</strong>\s*(.*?)</p>",
               r'<p class="mech">\1</p>', d, count=1)
    d = re.sub(r"<p><strong>Conversation sentence:</strong>\s*(.*?)</p>",
               r'<p class="convo">\1</p>', d, count=1)
    for lab in ("Lesson", "Challenge", "Practice"):
        d = re.sub(rf"<p><strong>{lab}:</strong>\s*(.*?)</p>", rf'<h2>{lab}</h2><p>\1</p>', d)
        d = re.sub(rf"<p><strong>{lab}:</strong></p>", rf"<h2>{lab}</h2>", d)
        d = re.sub(rf'<p class="runin"><strong>{lab}:</strong></p>', rf"<h2>{lab}</h2>", d)
    return d


def build(chapter_md, distillation_md, plates, out_pdf, title, dist_at="back", base_dir="."):
    body = []
    chapter_md = rasterise_plates(chapter_md, base_dir,
                                  os.path.dirname(os.path.abspath(out_pdf)) or ".")
    if dist_at != "back":
        raise ValueError("The approved chapter format puts distillation at the back")

    c = md_to_html(chapter_md)
    # Every chapter heading, not only the first: a whole manuscript passes
    # through here too, and count=1 left Chapters 2 onward without the kicker.
    c = format_headings(c)
    for marker, png, cap, (w, h) in plates:
        fig = (f'<figure class="plate"><img src="{os.path.basename(png)}" '
               f'width="{int(w)}" height="{int(h)}" alt="">'
               + (f"<figcaption>{_html.escape(cap)}</figcaption>" if cap else "")
               + "</figure>")
        if marker == "END":
            c += fig
        else:
            c = c.replace(marker, fig + marker, 1)
    body.append(f"<section>{c}</section>")

    if distillation_md and dist_at == "back":
        body.append('<section class="dist distback">'
                    + distillation_html(distillation_md,
                                        "Not part of the chapter &middot; working notes")
                    + '</section>')

    return render_html(''.join(body), out_pdf, title)


def render_html(body, out_pdf, title):
    """Print chapter and collection HTML with the same approved stylesheet."""
    doc = (f"<!doctype html><html><head><meta charset='utf-8'>"
           f"<title>{_html.escape(title)}</title><style>{CSS}\n{CHAPTER_CSS}</style></head>"
           f"<body>{body}</body></html>")
    html_path = os.path.splitext(out_pdf)[0] + ".html"
    open(html_path, "w", encoding="utf-8").write(doc)
    # Use the same Playwright dependency as SVG rendering. Explicit close avoids
    # Chrome's CLI hanging after writing the PDF on macOS.
    subprocess.run(["node", "-e", PDF_JS, os.path.abspath(html_path),
                    os.path.abspath(out_pdf), CHROME],
                   env=dict(os.environ, NODE_PATH=node_modules()),
                   check=True, capture_output=True, timeout=90)
    return html_path


PDF_JS = """
const [html, pdf, exe] = process.argv.slice(1);
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({ executablePath: exe, args: ['--no-sandbox'] });
  try {
    const page = await browser.newPage();
    await page.goto(require('url').pathToFileURL(html).href);
    await page.evaluate(() => document.fonts.ready);
    await page.pdf({ path: pdf, preferCSSPageSize: true, printBackground: true,
                     tagged: true, outline: true });
  } finally { await browser.close(); }
})().catch(e => { console.error(e.stack); process.exit(1); });
"""


def main():
    import argparse
    ap = argparse.ArgumentParser(description="Render a chapter to PDF via headless Chromium.")
    ap.add_argument("--chapter", required=True)
    ap.add_argument("--distillation")
    ap.add_argument("--distillation-at", choices=["back"], default="back",
                    help="The shipped manuscript carries no distillation at all - it is "
                         "working apparatus that feeds the back-of-book practice guide. "
                         "Default back, and labelled, so a reader copy never opens on it.")
    ap.add_argument("--plate", action="append", default=[],
                    help="SVG[::marker][::caption]; marker END appends at the end")
    ap.add_argument("--out", required=True)
    ap.add_argument("--title", default="Chapter")
    a = ap.parse_args()

    if not os.path.exists(CHROME):
        print(f"chapter_pdf_local: no chromium at {CHROME}", file=sys.stderr)
        return 2

    outdir = os.path.dirname(os.path.abspath(a.out)) or "."
    os.makedirs(outdir, exist_ok=True)

    plates = []
    for spec in a.plate:
        parts = spec.split("::")
        svg = parts[0]
        marker = parts[1] if len(parts) > 1 and parts[1] else "END"
        cap = parts[2] if len(parts) > 2 else ""
        png = os.path.join(outdir, os.path.splitext(os.path.basename(svg))[0] + ".png")
        w, h = svg_to_png(svg, png)
        plates.append((marker, png, cap, (w, h)))
        print(f"  plate rasterised: {os.path.basename(png)}  {int(w)}x{int(h)} @3x")

    chapter = open(a.chapter, encoding="utf-8").read()
    dist = open(a.distillation, encoding="utf-8").read() if a.distillation else None
    html_path = build(chapter, dist, plates, a.out, a.title, a.distillation_at,
                      base_dir=os.path.dirname(os.path.abspath(a.chapter)))
    size = os.path.getsize(a.out)
    print(f"  html:  {html_path}")
    print(f"  pdf:   {a.out}  ({size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
