#!/usr/bin/env python3
"""
gaps_md.py - GAPS.md, generated from the inbox's gap items.

WHY THIS EXISTS
    Until 2026-10-04 GAPS.md was a hand-kept list of what the old pipeline does
    that this house does not, living beside the inbox and the parking lot: three
    places the author had to remember to look. The gaps now live in the inbox as
    items of kind `gap` (say "work the inbox"). GAPS.md stays only because the
    manual, FLOW.md and the /gw menu point at it, and a file that calls itself a
    view of something else needs a script deriving it, or it drifts: the retired
    citation-manifest.md failure. This is that script.

USAGE
    python3 scripts/gaps_md.py            # rewrite GAPS.md
    python3 scripts/gaps_md.py --check    # exit 1 if GAPS.md is not what this would write

The output carries no date, so --check is stable: it fails only when an item changed.
"""

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)

import inbox  # noqa: E402

TARGET = os.path.join(REPO, "GAPS.md")

HEADER = """# Gaps

*Generated by `scripts/gaps_md.py` from the inbox's gap items. Do not edit this
file: say "work the inbox" to see, change or close them. It states what the old
pipeline does that this house does not, each with the trigger that should close
it. Say "not yet, and here is what it waits on" rather than discovering a gap
when he needs it.*
"""


def render(items):
    gaps = [i for i in items if i.get("kind") == "gap"]
    open_ = [i for i in gaps if i["status"] == "open"]
    done = [i for i in gaps if i["status"] == "resolved"]
    L = [HEADER]
    L.append(f"## Open ({len(open_)})\n")
    for i in open_:
        L.append(f"### {i['title']}\n")
        L.append(f"**Trigger:** {i['trigger']}\n")
        body = i["body"].split("\n", 1)[1].strip() if i["body"].startswith("#") else i["body"]
        body = "\n".join(l for l in body.split("\n") if not l.startswith("*Migrated"))
        L.append(body.strip() + "\n")
    L.append(f"## Built since the audit ({len(done)})\n")
    L.append("| Was missing | Now |\n|---|---|")
    for i in done:
        body = i["body"].split("\n", 1)[1].strip() if i["body"].startswith("#") else i["body"]
        body = " ".join(l for l in body.split("\n") if l.strip() and not l.startswith("*Migrated"))
        L.append(f"| {i['title']} | {body} |")
    return "\n".join(L).rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser(description="Generate GAPS.md from inbox gap items.")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    want = render(inbox.load_all())
    if a.check:
        have = open(TARGET, encoding="utf-8").read() if os.path.isfile(TARGET) else ""
        if have != want:
            print("gaps_md: GAPS.md is stale. Regenerate: python3 scripts/gaps_md.py", file=sys.stderr)
            return 1
        print("gaps_md: GAPS.md matches the inbox's gap items.")
        return 0
    with open(TARGET, "w", encoding="utf-8") as fh:
        fh.write(want)
    print(f"gaps_md: wrote GAPS.md ({len(want.split())} words)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
