#!/usr/bin/env python3
"""
plate_brief.py - the plate brief, written from the chapter's own files.

WHY THIS IS A SCRIPT
    A plate may carry nothing the chapter does not say. When the Designer
    assembles the brief by hand it paraphrases, and the paraphrase becomes the
    plate's copy: "The tip feels sudden. It never is." is on the Ch8 plate and
    in no chapter. This script copies the chapter's own lines into one file,
    invents nothing, and leaves one section, Author additions, for words the
    author gives in session (dated). plate_check.py's grounded row reads the
    whole file, so an addition recorded here is grounded and one that is not
    is reported.

USAGE
    python3 scripts/plate_brief.py 8
    python3 scripts/plate_brief.py 8 --add "Cleaning the kitchen"   # his words, today
"""
import argparse
import collections
import datetime
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import resolve_book  # noqa: E402

STOP = set("""the a an and or but if then than that this these those it its he she her his him
you your yours we our they them their what which who whom when where why how not no yes so
as at by for from in into of off on onto out over to up with without about after before
again all any are be been being both can could did do does doing done down during each few
had has have having here just more most much must my me now once only other own same should
some still such there through too under until very was were will would is am been""".split())


def section(text, label):
    m = re.search(r'^\*\*%s:\*\*\s*(.+?)\s*$' % re.escape(label), text, re.M)
    return m.group(1) if m else None


def nouns(prose, n=30):
    """The chapter's repeated concrete words, for the anchor image: no
    parsing, just the words that recur once stopwords and short words go."""
    words = re.findall(r"[A-Za-z][a-z']{3,}", prose)
    c = collections.Counter(w.lower() for w in words if w.lower() not in STOP)
    return [w for w, k in c.most_common(n) if k >= 3]


def main():
    ap = argparse.ArgumentParser(description="Write runs/chNN/plate-brief.md from the chapter's files.")
    ap.add_argument("chapter", type=int)
    ap.add_argument("--add", action="append", default=[],
                    help="the author's own words for the plate, recorded with today's date")
    a = ap.parse_args()

    root, _, _ = resolve_book.resolve(resolve_book.load_config())
    if not root:
        print("plate_brief: no book repo resolvable.", file=sys.stderr)
        return 2
    rel = resolve_book.inspect(root, require_okf=False)["info"]["bookRootRelative"]
    B = os.path.join(root, rel)
    tag = "ch%02d" % a.chapter
    run = os.path.join(REPO, "runs", tag)
    os.makedirs(run, exist_ok=True)
    cands = [run, os.path.join(B, "chapters", tag)]

    def find(name):
        for d in cands:
            p = os.path.join(d, name)
            if os.path.isfile(p):
                return p, io.open(p, encoding="utf-8").read()
        return None, None

    dpath, dist = find("distillation.md")
    ppath, prose = find("refined.md")
    if dist is None or prose is None:
        print("plate_brief: %s needs distillation.md and refined.md (looked in %s)" % (tag, ", ".join(cands)),
              file=sys.stderr)
        return 1
    _, draft = find("draft.md")
    fam = re.search(r"metaphor_family:\s*([^`\n]+)", draft or prose or "")

    out = os.path.join(run, "plate-brief.md")
    existing = io.open(out, encoding="utf-8").read() if os.path.isfile(out) else ""
    adds = re.findall(r"^- (\d{4}-\d{2}-\d{2} \d{2}:\d{2}): (.+)$",
                      existing.split("## Author additions", 1)[1] if "## Author additions" in existing else "", re.M)
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    adds += [(now, w) for w in a.add]

    lines = [
        "# Plate brief, Chapter %d" % a.chapter,
        "",
        "Generated by scripts/plate_brief.py on %s from %s and %s. Nothing here is" % (now, os.path.relpath(dpath, REPO), os.path.relpath(ppath, REPO)),
        "invented; a plate may use these words and the chapter's, and nothing else.",
        "The Author additions section is the one place words from the author's own",
        "mouth are recorded, with the date; plate_check.py's grounded row reads it.",
        "",
        "**Title (the Mechanism, word for word):** %s" % (section(dist, "Mechanism") or "[missing]"),
        "**Conversation sentence:** %s" % (section(dist, "Conversation sentence") or "[missing]"),
        "**Lesson:** %s" % (section(dist, "Lesson") or "[missing]"),
        "**Challenge:** %s" % (section(dist, "Challenge") or "[missing]"),
        "**Anchor image (metaphor_family):** %s" % (fam.group(1).strip() if fam else "none declared; find the chapter's one recurring image in the prose"),
        "",
        "## The chapter's own recurring words",
        "",
        ", ".join(nouns(prose)) or "(none recur three times)",
        "",
        "## The standard",
        "",
        "A man who never read the chapter looks at the plate on his phone for ten",
        "seconds. What he takes away is the Conversation sentence, or the plate has",
        "failed. The drawing carries the argument; captions name what is drawn.",
        "",
        "## Author additions",
        "",
    ]
    lines += ["- %s: %s" % (d, w) for d, w in adds] or ["(none yet)"]
    io.open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print("plate_brief: %s (%d author addition%s)" % (os.path.relpath(out, REPO), len(adds), "" if len(adds) == 1 else "s"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
